[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings =["@safe-contracts/=lib/safe-contracts/contracts"]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
